#!/bin/bash
sudo apt-get -y update
sudo apt-get -y install nodejs npm
sudo npm install --force -g webpack

cd /home/ubuntu/node.bellew.net
npm update
npm run build
sudo systemctl enable /home/ubuntu/node.bellew.net/configure/www-bellew-net.service
sudo systemctl daemon-reload
sudo systemctl restart www-bellew-net.service
